Create SECURITY.md
discord-modmail/modmail pull request #20
Opened 2021-06-19 06:38 UTC by bast0006

2021-06-19 06:39 UTC, bast0006 commented
Boilerplate. Add more if you think we need it.

2021-06-19 11:46 UTC, dawnofmidnight submitted a review, later dismissed

2021-06-19 11:46 UTC, dawnofmidnight commented on SECURITY.md
> +Please report vulnerabilities here on discord using the
Shouldn't it say "here on GitHub"?

2021-06-19 11:46 UTC, dawnofmidnight commented on SECURITY.md
> +see this and are sure the report-this flow is nonfunctional, join our [discord](https://discord.gg/3f7jBUXdxw)
Make sure to capitalize Discors

2021-07-28 01:17 UTC, onerandomusername requested changes
What is the "report security vulnerability" flow?

2021-07-28 22:37 UTC, bast0006 commented
Oh for the love of

2021-07-29 02:19 UTC, onerandomusername approved these changes
LGTM

2021-07-29 02:20 UTC, merged