Repo merge
discord-modmail/modmail pull request #7
Opened 2021-05-25 18:40 UTC by bast0006

2021-05-25 18:41 UTC, bast0006 commented
This needs post merge cleanup pretty badly

2021-05-25 19:15 UTC, onerandomusername requested changes
This looks pretty good. 

I think that the site stuff should all be moved to a `/site` folder. If that name causes conflicts, `/website` would be another possible name.

One possibilty to launch both the bot and the site would be to use starlette's on_start methods, but I think we need to have a strategy for being able to run just the bot or just the site.

2021-05-25 19:16 UTC, onerandomusername commented
I left out of my review, but pyproject and poetry lock need to be updated.

2021-05-26 02:08 UTC, Shivansh-007 approved these changes

2021-05-26 02:08 UTC, merged